### ISSUE TITLE
react-flatifycss是我做前端开发用到最好的前端库

### ISSUE THREAD

**Issue by obeiip** [amir2mi/react-flatifycss#16]
react-flatifycss是我做前端开发用到最好的前端库，希望可以继续完善一些功能，感谢开发人员的辛苦付出。
另外有几个问题需要反馈一下：
1、Radio 、Select、Checkbox等一些组件不能正常显示代码，导致无法使用，很烦恼啊
2、https://react.flatifycss.com ，左上角的logo无法显示

**Comment by amir2mi** [comment]
Hi
I will look into code preview, thanks for reporting.
The logo is served by GitHub, probably that is related to your network.

**Comment by amir2mi** [comment]
Well that was an issue about importing wrong components in form category of the storybook, now it is fixed.
