### ISSUE TITLE
建议react-flatifycss，兼容docusaurus的css

### ISSUE THREAD

**Issue by obeiip** [amir2mi/react-flatifycss#17]
我目前用react-flatifycss+docusaurus开发单页面应用，可是两者的css文件样式不统一，导致开发的网页很难保持css的统一，为开发造成很多不方便。建议在docusaurus默认custom.css文件中添加react-flatifycss的样式，可以让程序员更好更快速的开发前端页面。

**Comment by amir2mi** [comment]
I agree that changing Docusaurus styles can be a bit challenging, but I'm sure they've added better ways to customize, I did it years ago on v2-beta as you can see here:
https://github.com/amir2mi/flatifycss/blob/master/website/src/css/custom.css
